version: '3.3'
services:
  repairtracking-db:
    image: mysql:5.7
    restart: always
    container_name: repairtracking-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1A2B3C4E
      MYSQL_DATABASE: RepairTracking
    volumes: 
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080
    depends_on:
      - repairtracking-db